name: Post commits to Discord

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout (full history for diffs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Discord message
        id: build
        shell: bash
        run: |
          REPO="${{ github.repository }}"
          BRANCH="${{ github.ref_name }}"
          ACTOR="${{ github.actor }}"
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          # Commit summaries from the event payload
          COMMITS=$(jq -r '.commits[] | "- \(.id[0:7]) \(.message | gsub("\\n"; " ")) by \(.author.username // .author.name)"' "$GITHUB_EVENT_PATH" || true)

          # Changed files across the push range (handle first-push case)
          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE" ]; then
            CHANGES=$(git diff --name-status "$AFTER^!" | head -n 50 || true)
          else
            CHANGES=$(git diff --name-status "$BEFORE" "$AFTER" | head -n 50 || true)
          fi

          {
            echo "content<<EOF"
            echo "📦 $REPO → $BRANCH"
            echo
            echo "Pushed by **$ACTOR**"
            echo
            echo "**Commits**"
            echo "$COMMITS"
            echo
            echo "**Changed files**"
            echo '```'
            echo "$CHANGES"
            echo '```'
            echo
            echo "https://github.com/$REPO/compare/$BEFORE...$AFTER"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Send to Discord
        uses: tsickert/discord-webhook@v5.4.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: ${{ steps.build.outputs.content }}
